name: Crowdin Download

on:
  schedule:
    - cron: '0 */23 * * 0,3,6' # At the 23 hour on Sunday, Wednesday, and Saturday- https://crontab.guru/#0_*/23_*_*_0,3,6
  workflow_dispatch:

jobs:
  crowdin:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Crowdin pull
        uses: crowdin/github-action@v2.3.0
        with:
          upload_sources: false
          upload_translations: false
          download_sources: true
          download_translations: true
          create_pull_request: false
          push_translations: true
          crowdin_branch_name: 'main'
          #download_translations_args: -b main
          localization_branch_name: 'main'

          # GitHub Commits Advanced Settings
          commit_message: 'New Language Translations'
          pull_request_assignees: 'Crowdin Bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
