name: Crowdin Download

on:
  schedule:
    - cron: "0 18 * * *" # At 12 o'clock EST
  workflow_dispatch:

jobs:
  Download:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2 # Make sure you are using the latest version of checkout action

      - name: Crowdin pull
        uses: crowdin/github-action@v2.3.0
        with:
          upload_sources: false
          upload_translations: false
          download_sources: true
          download_translations: true
          create_pull_request: false
          push_translations: true
          crowdin_branch_name: 'main'
          localization_branch_name: 'main'

          # GitHub Commit Advanced Settings
          commit_message: 'New Language Translations'
          pull_request_assignees: 'Crowdin Bot'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
